<!DOCTYPE html>
<html lang="en">
<head>
        <meta charset="UTF-8">
        <tittle>Instagram Login Page</tittle>
        <link rel="stylesheet" href="sttles.css">
</head>
<body>

<div class="wrapper">
         <div class="header">
         